version: '3.8'

services:
  doctorapp:
    build:
      context: .
      dockerfile: Dockerfile.prod
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    command: npm run start
