version: "3.8"

services:
  doctorapp:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true

    command: npm run dev
