"use client";

import React, { useState, useEffect } from "react";
import { useRouter, useParams } from "next/navigation"; // Import necessary hooks from next/navigation
import Header from "../_components/header"; // Adjust path as needed
import ChatMainContents from "../_components/chatMainContent"; // Adjust path as needed
import useSocket from "../../../socket.io/socket.io.initialization"; // Adjust path as needed
import TabComponent from "../_presc-components/tabs";

interface Message {
  id?: string; // Message ID is optional as it is auto-generated by MongoDB
  message: string;
  senderId: number;
  consultationId: number;
  isSent: boolean;
  read: boolean;
}

const ChatPage: React.FC = () => {
  const [messages, setMessages] = useState<Message[]>([]);
  const [loading, setLoading] = useState(true); // Loading state for messages
  const router = useRouter(); // Use router for redirection if needed
  const params = useParams(); // Extract the dynamic params from the URL
  const consultationId = params?.consultationId; // Get consultationId from the params

  console.log(`Consultation ID in page: ${consultationId}`);

  // Retrieve JWT token and userId from local storage
  const token =
    typeof window !== "undefined" ? localStorage.getItem("labass_token") : null;
  const userId =
    typeof window !== "undefined"
      ? localStorage.getItem("labass_userId")
      : null;

  console.log(`User ID: ${userId}`);

  // Initialize socket outside of the conditional logic
  const { socket, isConnected } = useSocket(
    "http://localhost:4000",
    token || ""
  ); // Replace with your backend URL

  // Redirect to login if token, userId, or consultationId is missing
  useEffect(() => {
    if (!token || !userId || !consultationId) {
      router.push("/login");
    }
  }, [token, userId, consultationId, router]);

  useEffect(() => {
    if (!socket || !userId || !consultationId) return;

    // Join the room dynamically based on consultationId
    socket.emit("joinRoom", { room: `${consultationId}` });

    // Load previous messages from the server (adjust the backend to support this)
    socket.emit(
      "loadMessages",
      { consultationId },
      (loadedMessages: Message[]) => {
        setMessages(loadedMessages);
        setLoading(false); // Stop loading once messages are fetched
      }
    );

    // Handle new messages received via socket
    const handleReceiveMessage = (newMessage: Message) => {
      setMessages((prevMessages) => [...prevMessages, newMessage]);

      // Emit acknowledgment to mark the message as read
      if (newMessage.senderId !== Number(userId)) {
        socket.emit("messageReceived", { messageId: newMessage.id });
      }
    };

    // Handle read status update
    const handleMessageStatus = ({
      messageId,
      read,
    }: {
      messageId: string;
      read: boolean;
    }) => {
      setMessages((prevMessages) =>
        prevMessages.map((msg) =>
          msg.id === messageId ? { ...msg, read: read } : msg
        )
      );
    };

    socket.on("receiveMessage", handleReceiveMessage);
    socket.on("messageStatus", handleMessageStatus);

    // Cleanup: Remove socket listener when component unmounts
    return () => {
      socket.off("receiveMessage", handleReceiveMessage);
      socket.off("messageStatus", handleMessageStatus);
    };
  }, [socket, userId, consultationId]);

  const handleSendMessage = (messageText: string) => {
    if (!isConnected || !socket || !userId) {
      console.error(
        "Socket is not connected or userId is missing. Message cannot be sent."
      );
      return;
    }

    // Prepare the message data to send without a message ID
    const newMessage: Message = {
      message: messageText,
      senderId: Number(userId), // Send userId
      consultationId: Number(consultationId), // Send consultationId
      isSent: false,
      read: false,
    };

    // Optimistically update the UI by adding the message locally
    setMessages((prevMessages) => [...prevMessages, newMessage]);

    // Send the message via socket, explicitly passing the room (consultationId)
    socket.emit(
      "sendMessage",
      {
        room: `${consultationId}`, // Add the room (consultationId) explicitly
        message: messageText,
        consultationId: Number(consultationId),
        senderId: Number(userId),
      },
      (response: { messageId: string }) => {
        // Update the message with the correct ID from the backend
        setMessages((prevMessages) =>
          prevMessages.map((msg) =>
            msg === newMessage
              ? { ...msg, id: response.messageId, isSent: true }
              : msg
          )
        );
      }
    );
  };

  // Loading spinner to display while messages are being loaded
  if (loading) {
    return (
      <div className="flex justify-center items-center h-screen">
        <div
          className="spinner-border animate-spin inline-block w-8 h-8 border-4 rounded-full"
          role="status"
        >
          <span className="visually-hidden">...</span>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-screen bg-white">
      <TabComponent />

      {/* <Header title="استشارة فورية" showBackButton={true} /> */}
      {consultationId && (
        <ChatMainContents
          consultationId={Number(consultationId)} // Pass consultationId to ChatMainContents
          showActions={true}
          messages={messages}
          handleSendMessage={handleSendMessage}
        />
      )}
    </div>
  );
};

export default ChatPage;
